- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: ansible-rg
      location: westeurope

  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: ansible-rg
      name: ansible-vnet
      address_prefixes: "10.0.0.0/16"
  
  - name: Add subnet
    azure_rm_subnet:
      resource_group: ansible-rg
      name: ansible-subnet
      address_prefix: "10.0.1.0/24"
      virtual_network: ansible-vnet
      
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: ansible-rg
      allocation_method: Static
      name: ansible-public-ip
    register: output_ip_address
    
  - name: Dump public IP for VM which will be created
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."
      
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: ansible-rg
      name: ansible-net-security-group
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
          
  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: ansible-rg
      name: ansible-nic
      virtual_network: ansible-vnet
      subnet: ansible-subnet
      public_ip_name: ansible-public-ip
      security_group: ansible-net-security-group
      
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: ansible-rg
      name: ansible-centos-vm
      vm_size: Standard_B1s
      admin_username: azureuser
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      network_interfaces: ansible-nic
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.5'
        version: latest

