---
- name: Get dynamic host list
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - include: get-hosts-tasks.yml

- name: Docker Client Set up
  hosts: centosservers
  gather_facts: no
  tasks:
    - name: Make .docker-{{ inventory_hostname }} directory for docker certs
      file:
        path: './.docker-{{ inventory_hostname }}'
        state: 'directory'
      delegate_to: localhost

    - name: Make .docker-{{ inventory_hostname }}/client.rc file
      file:
        path: './.docker-{{ inventory_hostname }}/client.rc'
        state: 'touch'
      delegate_to: localhost

    - name: Add Environment variables to .docker-{{ inventory_hostname }}/client.rc
      lineinfile:
        dest: './.docker-{{ inventory_hostname }}/client.rc'
        line: 'export DOCKER_TLS_VERIFY=1\nexport DOCKER_CERT_PATH=./.docker-{{ inventory_hostname }}/\nexport DOCKER_HOST=tcp://{{ inventory_hostname }}:2376\n'
        state: 'present'
      delegate_to: localhost

- name: Docker Daemon Set up
  hosts: centosservers
  gather_facts: no
  remote_user: azureuser
  become: yes
  become_method: sudo
  become_user: root
  roles:
    - role: role-secure-docker-daemon
      dds_host: "{{ inventory_hostname }}"
      dds_server_cert_path: /etc/docker
      dds_restart_docker: no
  tasks:
    - name: fetch ca.pem from daemon host
      fetch:
        src: /root/.docker/ca.pem
        dest: ./.docker-{{ inventory_hostname }}/
        fail_on_missing: yes
        flat: yes
    - name: fetch cert.pem from daemon host
      fetch:
        src: /root/.docker/cert.pem
        dest: ./.docker-{{ inventory_hostname }}/
        fail_on_missing: yes
        flat: yes
    - name: fetch key.pem from daemon host
      fetch:
        src: /root/.docker/key.pem
        dest: ./.docker-{{ inventory_hostname }}/
        fail_on_missing: yes
        flat: yes

    - name: Modify service file
      lineinfile:
        dest: /usr/lib/systemd/system/docker.service
        regexp: "ExecStart=/usr/bin/dockerd -H fd://"
        line: ExecStart=/usr/bin/dockerd -H fd:// --tlsverify --tlscacert=/etc/docker/ca.pem --tlscert=/etc/docker/server-cert.pem --tlskey=/etc/docker/server-key.pem -H=0.0.0.0:2376 --containerd=/run/containerd/containerd.sock

    - name: Remove client certs from daemon host
      file:
        path: /root/.docker
        state: absent

    - name: Reload Docker daemon
      systemd:
        name: docker
        state: restarted
        daemon_reload: yes

