###
# initial source https://www.epilis.gr/en/blog/2017/08/09/extending-root-fs-whole-farm/
###
---

  - name: Get partition information
    parted:
      device: "{{dev}}"
    register: partinfo
    become: yes
  - debug: var=partinfo.partitions[-1].end
  
  - name: "Create a new partition after {{partinfo.partitions[-1].end}}KiB"
    parted:
      part_start: "{{partinfo.partitions[1].end}}KiB"
      device: "{{dev}}"
      number: "{{partinfo.partitions[-1].num + 1}}"
      flags: [ lvm ]
      state: present
    become: yes
    
  - name: Probe kernel about partition table changes
    command: partprobe
    become: yes
    
  - name: Add the partition to the volume group
    lvg:
      vg: "{{vg_name}}"
      pvs: "{{dev}}{{partinfo.partitions[-1].num}},{{dev}}{{partinfo.partitions[-1].num + 1}}"
    become: yes
    
  - name: Extend LVM to the whole volume group
    lvol:
      vg: "{{vg_name}}"
      lv: "{{lv_name}}"
      size: +100%FREE
    become: yes
    
  - name: Extend the filesystem
    filesystem:
      fstype: ext4
      dev: "/dev/mapper/{{vg_name}}-{{lv_name}}"
      resizefs: yes
    become: yes
